### ISSUE TITLE
env.parallel overrides serial decorator

### ISSUE THREAD

**Issue by mikeshultz** [fabric/fabric#1570]
It seems that `env.parellel` overrides the `serial` decorator. Here's a simple test case: 

    from fabric.api import env, run
    from fabric.decorators import task, serial

    env.parallel = True

    @task
    @serial
    def test_task():
        run('touch /tmp/t && rm /tmp/t')

Results of `fab -H testmachine.example.com test_task`: 

    [testmachine.example.com] Executing task 'test_task'
    [testmachine.example.com] run: touch /tmp/t && rm /tmp/t

    Fatal error: Needed to prompt for a connection or sudo password (host: testmachine.example.com), but input would be ambiguous in parallel mode

    Aborting.

Expected behavior would be a password prompt.

    # fab --version
    Fabric 1.13.1
    Paramiko 2.1.2

Let me know if I'm missing something obvious.  Thanks

**Comment by ploxiln** [comment]
The task is still executed serially, but it seems that the prompt-check doesn't know that. If your tasks don't require a prompt, I expect it'll work :)

**Comment by mikeshultz** [comment]
My example might not be the best, then, but there are tasks that require a prompt(like distributing SSH keys for the first time) that you can't really work around.  For this one effort, I just did `env.parallel = False` but thought I'd report this issue since I can't be the only one to run into this.

**Comment by ploxiln** [comment]
It makes sense to report, just want to clarify that this is a bug in the prompt.

**Comment by bitprophet** [comment]
Confirmed that the actual behavior should be working as you describe & the decorator is taking effect re: execution: http://docs.fabfile.org/en/1.13/api/core/decorators.html#fabric.decorators.serial

> This decorator takes precedence over the global value of env.parallel.

So yes, I bet @ploxiln is right and the issue is that the prompt machinery is checking `env.parallel`. (It may not have any good handle on the current task being executed, meaning it may not be trivial to solve; I'd have to check whether we expose that in a useful fashion. This is one of the many problems with the design of the codebase...something the more OO v2 might help with, though I haven't implemented serial/parallel mixing there yet.)

**Comment by ocervell** [comment]
I just ran into this.
I have a pre-task setting  `env.parallel` (True for remote, False for localhost) and a task decorated with `@serial`, but it still gets executed in parallel.
